name: panorama_viewer
description: Panorama Viewer - A 360-degree panorama viewer.
# pub.dev using `flutter pub publish`.
version: 1.0.3
homepage: https://github.com/dariocavada/panorama_viewer

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  dchs_motion_sensors: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
